name: K6 Load Test

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0,2,4,6,8,10,12,14,16,18 * * *'

jobs:
  k6-load-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run K6 cloud load test
        run: k6 cloud run testtwo.js
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}